name: Run Otter Assign

on:
  push:
    branches:
      - main
    paths:
      - raw_notebooks/**
  pull_request:

env: 
  NOTEBOOK_DIR: raw_notebooks
  OUTPUT_DIR: generated_notebooks
  REQUIREMENTS_FILE: requirements.txt
  REPO_FOR_PUSH: sean-morris/otterizing-jupyter-notebooks.git
  SCRIPT_PATH: .github/scripts

jobs:
  otter-assign:
    runs-on: ubuntu-latest
    container:
      image: seansmorris/ubuntu-playwright:latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Set GIT_SAFE_DIRS
      run: |
        export GIT_SAFE_DIRS="/__w/otterizing-jupyter-notebooks/otterizing-jupyter-notebooks"
        git config --global --add safe.directory /__w/otterizing-jupyter-notebooks/otterizing-jupyter-notebooks

    - name: Create virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
    
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: venv
        key: ${{ runner.os }}-pip-${{ hashFiles('**/$REQUIREMENTS_FILE') }}
        restore-keys: |
          ${{ runner.os }}-pip-
  
    - name: Install Chromium via Playwright
      run: |
        playwright install chromium

    - name: Config virtual environment
      run: |
        bash $SCRIPT_PATH/config_env.sh
    
    - name: Run otter assign changed subfolders
      run: |
        source venv/bin/activate
        python3 $SCRIPT_PATH/process_otterrize_notebooks.py
  
    - name: Clean MetaData from notebooks
      run: |
        source venv/bin/activate
        nb-clean clean $NOTEBOOK_DIR/ -o -e  
        nb-clean clean $OUTPUT_DIR/ -o -e

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Automated commit from GitHub Action"
        git remote set-url origin https://$GITHUB_TOKEN@github.com/$REPO_FOR_PUSH
        #git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
